[package]
name = 'Airpay'
version = '1.0.0'
#[dependencies.AptosFramework]
#git = 'https://github.com/aptos-labs/aptos-core.git'
#rev = 'devnet'
#subdir = 'aptos-move/framework/aptos-framework'

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }
Switchboard = { git = "https://github.com/switchboard-xyz/switchboard-aptos-public.git", subdir = "switchboard", rev = "24ed79c512de3a3455679ba3c66544246cd07959"}


[addresses]
hypermatter ='0x1'
switchboard = '0x2'
